INSERT INTO distrito(id, nome, provincia) VALUES (1, 'Báruè', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (2, 'Guro', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (3, 'Macossa', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (4, 'Manica', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (5, 'Sussundenga', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (6, 'Mussurize', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (7, 'Gondola', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (8, 'Vandizi', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (9, 'Tambara', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (10, 'Chimoio', 'Manica');
INSERT INTO distrito(id, nome, provincia) VALUES (11, 'Changara', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (12, 'Tete', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (13, 'Moatize', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (14, 'Cahora Bassa', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (15, 'Chiuta', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (16, 'Maravia', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (17, 'Zumbo', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (18, 'Tsangano', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (19, 'Angonia', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (20, 'Macanga', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (21, 'Chinfunde', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (22, 'Mágoè', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (23, 'Mutarara', 'Tete');
INSERT INTO distrito(id, nome, provincia) VALUES (24, 'Dondo', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (25, 'Machanga', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (26, 'Chibabava', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (27, 'Búzi', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (28, 'Beira', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (29, 'Nhamatanda', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (30, 'Cheringoma', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (31, 'Muanza', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (32, 'Gorongosa', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (33, 'Marringue', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (34, 'Chemba', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (35, 'Caia', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (36, 'Marrumeu', 'Sofala');
INSERT INTO distrito(id, nome, provincia) VALUES (37, 'Matutuine', 'Maputo');
INSERT INTO distrito(id, nome, provincia) VALUES (38, 'Boane', 'Maputo');
INSERT INTO distrito(id, nome, provincia) VALUES (39, 'Maputo', 'Maputo');
INSERT INTO distrito(id, nome, provincia) VALUES (40, 'Namaacha', 'Maputo');
INSERT INTO distrito(id, nome, provincia) VALUES (41, 'Manhiça', 'Maputo');
INSERT INTO distrito(id, nome, provincia) VALUES (42, 'Marracuene', 'Maputo');
INSERT INTO distrito(id, nome, provincia) VALUES (43, 'Moamba', 'Maputo');
INSERT INTO distrito(id, nome, provincia) VALUES (44, 'Magude', 'Maputo');
INSERT INTO distrito(id, nome, provincia) VALUES (45, 'Bilene', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (46, 'Xai-xai', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (47, 'Mandlakazi', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (48, 'Chokwe', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (49, 'Guija', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (50, 'Chibuto', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (51, 'Mabalane', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (52, 'Massingir', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (53, 'Chicualacuala', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (54, 'Chibuto', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (55, 'Massangena', 'Gaza');
INSERT INTO distrito(id, nome, provincia) VALUES (56, 'Zavala', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (57, 'Inharrime', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (58, 'Jangamo', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (59, 'Homoine', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (60, 'Panda', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (61, 'Morrumbene', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (62, 'Inahambane', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (63, 'Funhalouro', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (64, 'Massinga', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (65, 'Vilankulo', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (66, 'Inhassoro', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (67, 'Govuro', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (68, 'Mabote', 'Inhambane');
INSERT INTO distrito(id, nome, provincia) VALUES (69, 'Murrumbala', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (70, 'Nicuadala', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (71, 'Mopeia', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (72, 'Chinde', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (73, 'Inhassunge', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (74, 'Mamacurra', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (76, 'Mocuba', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (77, 'Ile', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (78, 'Pebane', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (79, 'Lugela', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (80, 'Gile', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (81, 'Alto Molocue', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (82, 'Gurue', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (83, 'Milange', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (84, 'Namarroi', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (85, 'Maganja da Costa', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (86, 'Moma', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (87, 'Murrupula', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (88, 'Angoche', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (89, 'Mugovolos', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (90, 'Mogincual', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (91, 'Mussiril', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (92, 'Ilha de Moçambique', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (93, 'Miconta', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (94, 'Cidade de Nampula', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (95, 'Ribaue', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (96, 'Malema', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (97, 'Muecate', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (98, 'Nacarroa', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (99, 'Nacala-a-velha', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (100, 'Erati', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (101, 'Memba', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (102, 'Nacala - Porto', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (103, 'Macuburi', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (104, 'Lalaua', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (105, 'Monapo', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (106, 'Meconta', 'Nampula');
INSERT INTO distrito(id, nome, provincia) VALUES (107, 'Mecanhelas', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (108, 'Cuamba', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (109, 'Metarica', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (110, 'Mandimba', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (111, 'Nipepe', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (112, 'Maua', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (113, 'Ngauma', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (114, 'Majune', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (115, 'Marrupa', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (116, 'Lichinga', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (117, 'Mecula', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (118, 'Mavago', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (119, 'Sanga', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (120, 'Lago', 'Niassa');
INSERT INTO distrito(id, nome, provincia) VALUES (121, 'Namuno', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (122, 'Chiure', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (123, 'Balama', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (124, 'Ancuabe', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (125, 'Mecufi', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (126, 'Cidade de Pemba', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (127, 'Quissanga', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (128, 'Quissanga', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (129, 'Montepuez', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (130, 'Meluco', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (131, 'Ibo', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (132, 'Macomia', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (133, 'Muidumbe', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (134, 'Moeda', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (135, 'Mocimboa da Praia', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (136, 'Nangade', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (137, 'Palma', 'Cabo Delegado');
INSERT INTO distrito(id, nome, provincia) VALUES (138, 'Quilimane', 'Zambézia');
INSERT INTO distrito(id, nome, provincia) VALUES (139, 'Machaze', 'Manica');

INSERT INTO public.permissao(id, descricao, nome)VALUES (1, 'ROLE_ALUNO', 'ALUNO');
INSERT INTO public.permissao(id, descricao, nome)VALUES (2, 'ROLE_SECRETARIO', 'SECRETARIO');
INSERT INTO public.permissao(id, descricao, nome)VALUES (3, 'ROLE_PROFESSOR', 'PROFESSOR');
INSERT INTO public.permissao(id, descricao, nome)VALUES (4, 'ROLE_DIRECTOR_ADJUNTO', 'DIRECTOR ADJUNTO DA ESCOLA');
INSERT INTO public.permissao(id, descricao, nome)VALUES (5, 'ROLE_DIRECTOR', 'DIRECTOR DA ESCOLA');
INSERT INTO public.permissao(id, descricao, nome)VALUES (6, 'ROLE_DIRECTOR_DISTRITO', 'DIRECTOR DO  DISTRITO');
INSERT INTO public.permissao(id, descricao, nome)VALUES (7, 'ROLE_PROGRAMADOR', 'PROGRAMADOR');


INSERT INTO usuario(
	id, ativo,  email, estadocivil, login,  nome, senha, sexo, ocultar_email,  distrito_id, senhaalterada)
	VALUES (1, true,'agostinhojolocholo64@gmail.com', 'SOLTEIRO', 'programador', 'AGOSTINHO B. JOLOCHOLO', '$2a$10$HUVwpO9LTYF7TqzeajTrt.c6sUdA/924pGgP1vxPGbKlGX/PM2L/K', true, true,  1, true);
INSERT INTO funcionario(id)
	VALUES ( 1);
INSERT INTO usuario_permissao(id_usuario, id_permissao) VALUES (1, 7);